# Generated by Django 5.1.4 on 2025-01-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0001_initial'),
    ]

    operations = [

        migrations.CreateModel(
            name='Album_Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_album', models.IntegerField()),
                ('id_cancion', models.IntegerField()),
            ],
        ),

        migrations.AlterField(
            model_name='cancion',
            name='genero',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
