# Generated by Django 5.1.4 on 2025-01-20 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0002_album_album_temp_genero_alter_cancion_genero'),
    ]

    operations = [

    ]
