# Generated by Django 5.1.4 on 2025-01-20 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0003_alter_cancion_album'),
    ]

    operations = [

    ]
