# Generated by Django 5.1.4 on 2025-01-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0003_alter_cancion_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
