# Generated by Django 5.1.4 on 2025-01-21 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0004_alter_cancion_album'),
    ]

    operations = [

    ]
