# Generated by Django 5.1.4 on 2025-01-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0005_alter_cancion_genero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genero_temp',
        ),
    ]
