# Generated by Django 5.1.4 on 2025-01-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0005_alter_cancion_album'),
        ('bdSpotify', '0006_delete_genero_temp'),
    ]

    operations = [
    ]
