# Generated by Django 5.1.4 on 2025-01-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0008_alter_cancion_album_alter_cancion_genero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album_Temp',
        ),
    ]
