# Generated by Django 5.1.4 on 2025-01-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0009_delete_album_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album_Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_album', models.IntegerField()),
                ('id_cancion', models.IntegerField()),
            ],
        ),
    ]
