# Generated by Django 5.1.4 on 2025-01-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0010_album_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
