# Generated by Django 5.1.4 on 2025-01-21 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0012_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdSpotify.album'),
        ),
    ]
