# Generated by Django 5.1.4 on 2025-01-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0013_alter_cancion_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album_Temp',
        ),
    ]
