# Generated by Django 5.1.4 on 2025-01-24 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0014_delete_album_temp'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_nacimiento__lte', datetime.datetime(2007, 1, 29, 9, 33, 59, 313192))), name='ch_edad_gte_18'),
        ),
    ]
