# Generated by Django 5.1.4 on 2025-01-24 08:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0015_usuario_ch_edad_gte_18'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usuario',
            name='ch_edad_gte_18',
        ),
        migrations.AlterField(
            model_name='lista',
            name='canciones',
            field=models.ManyToManyField(blank=True, null=True, to='bdSpotify.cancion'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdSpotify.usuario'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_nacimiento__lte', datetime.datetime(2007, 1, 29, 9, 42, 28, 100676))), name='ch_edad_gte_18'),
        ),
    ]
