# Generated by Django 5.1.4 on 2025-01-24 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0016_remove_usuario_ch_edad_gte_18_alter_lista_canciones_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usuario',
            name='ch_edad_gte_18',
        ),
        migrations.AlterField(
            model_name='lista',
            name='canciones',
            field=models.ManyToManyField(to='bdSpotify.cancion'),
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_nacimiento__lte', datetime.datetime(2007, 1, 29, 9, 43, 46, 640897))), name='ch_edad_gte_18'),
        ),
    ]
