# Generated by Django 5.1.4 on 2025-01-24 09:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0017_remove_usuario_ch_edad_gte_18_alter_lista_canciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='usuario',
            name='ch_edad_gte_18',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='canciones',
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_nacimiento__lte', datetime.datetime(2007, 1, 29, 10, 6, 58, 839028))), name='ch_edad_gte_18'),
        ),
        migrations.AddField(
            model_name='listacancion',
            name='cancion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdSpotify.cancion'),
        ),
        migrations.AddField(
            model_name='listacancion',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdSpotify.lista'),
        ),
        migrations.AddConstraint(
            model_name='listacancion',
            constraint=models.UniqueConstraint(fields=('cancion', 'lista'), name='clave_secundaria'),
        ),
    ]
