# Generated by Django 5.1.4 on 2025-01-24 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdSpotify', '0020_remove_usuario_ch_edad_gte_18_usuario_ch_edad_gte_18'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usuario',
            name='ch_edad_gte_18',
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_nacimiento__lte', datetime.datetime(2007, 1, 29, 10, 14, 19, 335794))), name='ch_edad_gte_18'),
        ),
    ]
